- lib/sfn/command/create.rb
I really want to be able to pipe `--print-only` output directly to [jq](http://stedolan.github.io/jq/), so here are some changes to facilitate that.
> Print only JSON when running create with --print-only

- README.md
- lib/sfn/command_module/base.rb
- sfn.gemspec
Launched a successful stack, but while polling I got a 500 error from AWS.  That triggered display_instance_failure in lib/sfn/config/inspect.rb, which blew up because it couldn't find any failed instances?
+ bundle exec sfn create -f stacks/cloudformation/output/databases_dr_us-west-2.json -r DatabaseInstancesEbsOptimized:true -r DatabaseInstanceType:r3.4xlarge -r ThirddatabaseInstancesEbsOptimized:true -r ThirddatabaseInstanceType:r3.4xlarge -d indigo-dr-tokumx-us-west-2-45
Unexpected error encountered (Miasma::Error::ApiError::RequestError: Internal Server Error) Retrying [retry count: 1]
ERROR: RuntimeError: 
[32m[Sfn]:[0m [1mCloud Formation:[0m [32mcreate[0m
[32m[Sfn]:[0m   -> [1mName:[0m indigo-dr-tokumx-us-west-2-45
[32m[Sfn]:[0m Events for Stack: …
> I think lines 77-end of lib/sfn/command/create.rb choke on 500 server errors from AWS

- lib/sfn/command_module/template.rb
Pretty good ripoff of the file selector but modified for using sparkle packs. Can probably refactor them both to use a generic chunk of code, but putting that off for a later date.
> [feature] Perform template selection via loaded sparkle packs

- lib/sfn/command.rb
- lib/sfn/command/print.rb
- lib/sfn/config.rb
- lib/sfn/config/print.rb
Adds an explicit command for printing generated templates instead of
relying on template related commands --print-only flag.
> [feature] Add print command (#31)

- lib/sfn/command/create.rb
- lib/sfn/command/describe.rb
- lib/sfn/command/destroy.rb
- lib/sfn/command/events.rb
- lib/sfn/command/inspect.rb
- lib/sfn/command/update.rb
- lib/sfn/command_module/base.rb
Addresses #47 and is applied to all commands
> Require name argument and error when not provided

- lib/sfn/command/update.rb
> Fix stack name reference when pulling compile state

- lib/sfn/command.rb
- lib/sfn/command/create.rb
- lib/sfn/command/diff.rb
- lib/sfn/command_module/template.rb
- lib/sfn/config.rb
- lib/sfn/config/diff.rb
- sfn.gemspec
Provides initial implementation of the `diff` command for use against
existing stacks prior to update.
> Add diff command

- lib/sfn/monkey_patch/stack.rb
Addresses issue described in #67
> Fix no-op apply-stack

- lib/sfn/planner/aws.rb
This addresses issue #83 where updates were not acting as expected
> Force a deep copy prior to dereferencing the template

- CONTRIBUTING.md
- Rakefile
- sfn.gemspec
- test/helper.rb
- test/sfn_test.rb
> tests / rake and contributing

- lib/sfn/config.rb
- test/specs/config_spec.rb
Addresses issue raised in #105 and fixes other Hash type
options as well.
> Fix hash type coerce

- lib/sfn/command_module/template.rb
- sfn.gemspec
This ensures expected pack ordering when populating collection of new template instance
> Use collection helper to apply settings

- lib/sfn/command/update.rb
- lib/sfn/planner/aws.rb
Covers items discussed in #122
> Prevent planner from causing updates to fail

- lib/sfn/callback/stack_policy.rb
* Removes policy update on delete (#120)
* Adds optional support for policy removal prior to update
> Update policy modifications in stack policy callback

- lib/sfn/command/inspect.rb
- lib/sfn/config/inspect.rb
Reports the name, public and/or private addresses, state of associated servers.
> add support for listing load balancers via inspect command

- lib/sfn/command/conf.rb
generated conf has wrong env var for secret
> conf generate azure block uses _client_secret

- docs/usage.md
Link was broken on http://www.sparkleformation.io/docs/sfn/usage.html
> Fix link for nested stack docs

- lib/sfn/command/update.rb
- lib/sfn/config/update.rb
- lib/sfn/planner.rb
- lib/sfn/planner/aws.rb
> Provide template diff content within plan

- lib/sfn/planner/aws.rb
> Use helpers for accessing deep hash path

- lib/sfn/command.rb
- lib/sfn/command/graph.rb
- lib/sfn/config.rb
- lib/sfn/config/graph.rb
This is initial poc of a fully working graph generator. It currently
only supports CFN templates due to magic values.
> Add graph command

- bin/sfn
- lib/sfn/command/update.rb
- lib/sfn/config.rb
- lib/sfn/config/update.rb
Addresses need requested in #156 for displaying plan information only without
need for user input to halt actual update request.
> Adds option to exit after plan display when using update command

- lib/sfn/command_module/template.rb
> Provide user friendly error message when nesting bucket not provided

- lib/sfn/command_module/template.rb
> Expand path prior to lookup to allow proper path matching

- lib/sfn/utils/stack_parameter_validator.rb
- test/specs/utils/stack_parameter_validator_spec.rb
> Support list types and validate all values in list

- .gitignore
- lib/sfn/command.rb
- sfn.gemspec
- test/specs/config/fail-auto-json/.sfn
- test/specs/config/fail-auto-ruby/.sfn
- test/specs/config/fail-auto-yaml/.sfn
- test/specs/config/no-ext/.sfn
- test/specs/config/yaml-ext/.sfn
- test/specs/sfn_bin_spec.rb
> Support loading configuration files with extensions

- bin/sfn
Prevents loading default gems re: #170
> Restrict bundler auto require to sfn group

- lib/sfn/command/create.rb
- lib/sfn/command/update.rb
- lib/sfn/command/validate.rb
- lib/sfn/command_module/template.rb
- lib/sfn/config/validate.rb
- sfn.gemspec
Addresses issue raised in #179 and sparkleformation/sparkle_formation#166
> Add support for object store root template storage

- lib/sfn/command/create.rb
- lib/sfn/command_module/stack.rb
- lib/sfn/config/update.rb
- lib/sfn/monkey_patch/stack.rb
Addresses issue #166 allowing customized mappings to be used when
applying stacks
> Allow for custom mapping on apply stack

- lib/sfn/command_module/stack.rb
- test/specs/command_module/stack_spec.rb
> Better parameter matching strategy when provided via config

- lib/sfn/command/lint.rb
Currently the puts does not go the the logger which prepends each line with [Sfn]
> Changing output from puts to info/fatal to match validate.

- lib/sfn/planner/aws.rb
- test/specs/planner_spec.rb
Add support for template condition processing within planner.
Fixes #229
> Support template conditions within planner

- lib/sfn/callback/stack_policy.rb
> Remove any explicit resource policies if not created

- README.md
This adds a link to the README for gitter.im
> Add link to gitter.im organization

- lib/sfn/command_module/template.rb
> Include validator module with template module

- lib/sfn/command/destroy.rb
> Only delete template if URL is string

- lib/sfn/command_module/template.rb
> Default provider to aws when unset

- lib/sfn/command/print.rb
- lib/sfn/config/print.rb
> Support YAML for print output

- lib/sfn/command/update.rb
- lib/sfn/command_module/template.rb
- lib/sfn/monkey_patch/stack.rb
- lib/sfn/planner/aws.rb
> Support compile time parameters with and without stack names.

- docs/callbacks.md
- lib/sfn/command_module/callbacks.rb
- test/rspecs/lib/command_module/callbacks_rspec.rb
> Add support for failed callbacks

- lib/sfn/config/validate.rb
> Support setting multiple values into compile time parameters

- lib/sfn/command/destroy.rb
> Validate stack is destroyed after destroy polling

- lib/sfn/command/trace.rb
- sfn.gemspec
Fixes sparkleformation/sparkle_formation#258
> Add timing output in trace
