sparkleformation/sfn

- lib/sfn/command_module/stack.rb
Fixes issue described in #20 where parameters is provided via
configuration resulting in merge where parameter would not be set
> [fix] Remove assumption of parameter availability (config provided)

- lib/sfn/command_module/template.rb
Allows for auto detection when unset. Fixes behavior described in issue
#33.
> [fix] Only provide root to pack when set.

- lib/sfn/command/update.rb
Properly orders the apply stack action after the new template has been
set into the model allowing for new parameters available in the updated
template to be properly populated if required.
> [fix] Apply stacks after modified template has been set on update

- docs/configuration.md
- docs/usage.md
A total of three characters affected \o/
Glad I could help :)
> fixed a couple of typos in docs

- lib/sfn/command/update.rb
- lib/sfn/command_module/template.rb
This adds support for using compile time parameters via the state
feature available within SparkleFormation's struct. Persists state for
expected behavior on update via dynamic output injection.
> Add support for compile time parameters

- lib/sfn/command_module/stack.rb
- lib/sfn/command_module/template.rb
Provides template location context when populating parameters which is
useful when using a deeply nested structure. Updates the way bucket
object keys are generated for storing nested templates to use full path
nesting names. Using the full path naming prevents name collisions where
multiple stacks in different trees may have the same logical resource ID.
> Parameter context and URL name generation

- lib/sfn/command_module/template.rb
> avoid printing compile time parameters ui message when using --print-only

- lib/sfn/command_module/stack.rb
Addresses #61 by only providing template path context when deeply nested
as shallow nesting will retain all parameters within the root stack.
> Only use root_path if handling a sparkle instance (deep nest)

- lib/chef/knife/knife_plugin_seed.rb
- lib/sfn/command.rb
- lib/sfn/command/conf.rb
- lib/sfn/config.rb
- lib/sfn/config/conf.rb
Adds command for displaying current configuration settings at runtime.
Fixes knife configuration setup to prevent defaults from stomping values
that should override.
> Add conf command. Fix knife command configuration.

- lib/sfn/command_module/base.rb
This allows defining retry behavior via the `retries` key within the
configuration. The original `retry` key is still supported (and has
precedence over the `retries` key) but this allows nicer usage within
ruby based configuration files.
> Add support for `retries` key in configuration

- lib/sfn/config.rb
- lib/sfn/config/update.rb
Make handling of hash type configurations more consistent when
re-formatting from CLI option. Deprecate the `:parameter` usage and add
a new `:parameters` option to properly make use of the underlying
implementation. Introduce new `:compile_parameters` option to allow
direct setting via CLI
> Add compile time parameters options. Make hash types more consistent.

- lib/sfn/planner/aws.rb
This addresses the issue described within PR #92. If no value is
available the resulting action should be a no-op.
> Only set output resource if name available within planner

- bin/sfn
A temporary workaround to enable side-loading commands into sfn.
> run Bundler.require if using Bundler

- lib/sfn/config/create.rb
The capabilities flag was an old flag that was replaced by
`--options` for provider specific create options. (re: #103)
> Remove deprecated capabilities flag

- lib/sfn/command.rb
- lib/sfn/command/init.rb
- lib/sfn/config.rb
- lib/sfn/config/init.rb
Command adds support for automatic project initialization. Creates
required directories, runs `conf` command to install default generated
.sfn configuration file. Creates Gemfile for project bundle and installs
the project bundle. re: #101
> Add init command for project initialization

- lib/sfn/command_module/template.rb
Addresses issue #111 to disable nested stack processing. Useful in situations
where a user wants to manually nest, or use a third party template.
> Allow nested stack processing to be disabled

- lib/sfn/planner/aws.rb
- test/specs/planner_spec.rb
> Cast all parameter values to string prior to planning

- lib/sfn/command_module/template.rb
- lib/sfn/config/update.rb
- lib/sfn/config/validate.rb
Properly build compile time parameters Hash on coercion. Allow
root stack name to be omitted. (#131)
> Fix compile time parameters from CLI

- lib/sfn/command/create.rb
- lib/sfn/command/events.rb
- lib/sfn/command/inspect.rb
- lib/sfn/command/update.rb
- lib/sfn/command_module/base.rb
- lib/sfn/command_module/template.rb
- lib/sfn/config/events.rb
- lib/sfn/monkey_patch/stack.rb
- lib/sfn/planner/aws.rb
- lib/sfn/provider.rb
- sfn.gemspec
Properly ensures stack artifacts are removed from deeply nested stacks
containing multiple stack resources.
> Prevent internal artifacts from remaining within template content

- lib/sfn/command/update.rb
On stack update set all values defined within config options into
stack instance prior to save. Provider driver can handle any needed
logic to disable invalid options. Provides #154
> Set config defined options into stack instance on update

- lib/sfn/command/update.rb
- lib/sfn/config/update.rb
This is an update to #157 which addresses #154. The update provided in #157
ended up breaking my stack updates. The cause was due to propagation of tags
to supported resources and my stack containing "missing resources". Because
this would be considered a breaking change I'm going to restrict this behavior
to being opt-in and will look to default the behavior on the next major release.
> Make API option merging on update behavior "opt-in"

- bin/sfn
Based off #172 but checks defined groups within definition instead
of dependency names. Retains existing default require behavior if
group not defined.
> Restrict automatic requires to sfn group if present

- lib/sfn/planner/aws.rb
- test/specs/planner_spec.rb
This changeset provides a starting point for refactoring the AWS planner
implementation for the initial POC to be a bit more verbose and to better
confine logic. It also adds integration of SparkleFormation::Resources which
includes support for conditional effect logic on resource property updates.
Initial planner refactor and integration of SparkleFormation resources
> Planner refactor and SparkleFormation resources integration

- docs/callbacks.md
http://www.sparkleformation.io/docs/sfn/callbacks.html has a couple messed up code blocks right now.
Not sure if this is the issue but seems like it could be.
> Fix code to all use tilde formatted blocks

- lib/sfn/command_module/template.rb
- lib/sfn/config/validate.rb
- test/specs/command_module/template_spec.rb
- test/specs/config/json-ext/.sfn.json
- test/specs/config/ruby-ext/.sfn.rb
When removing and merging config provided compile time values always
include underscore suffix when identifying match to prevent removal of
core parameter set.
> Include underscore suffix on compile time parameter matching

- lib/sfn/command_module/template.rb
Fixes: sparkleformation/sparkle_formation#202
> Prevent compile time state nesting within template set

- lib/sfn/command/update.rb
- lib/sfn/command_module/callbacks.rb
Tries to address issue https://github.com/sparkleformation/sfn/issues/202
- Makes callback output quiet when --print-only used.
- Makes update --print-only as quiet as create --print-only
> Quieter --print-only output - Issue #202

- lib/sfn/command_module/stack.rb
> Only use root name if SparkleFormation instance given

- lib/sfn/callback/stack_policy.rb
Hi,
After updating to sfn 3.0.26 I'm getting a weird error when updating my stacks:
```
...
[Sfn]: Applying stack policy to MyStack... error!
[ERROR]: Reason - undefined method `delete_if' for nil:NilClass
ERROR: NoMethodError: undefined method `delete_if' for nil:NilClass
/Users/pedrocarrico/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sfn-3.0.26/lib/sfn/callback/stack_policy.rb:83:in `save_stack_policy'
/Users/pedrocarrico/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sfn-3.0.26/lib/sfn/callback/stack_policy.rb:36:in `block (2 levels) in submit_policy'
/Users/pedrocarrico/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sfn-3.0.26/lib/sfn/callback.rb:43:in `run_action'
/Users/pedrocarrico/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sfn-3.0.26/lib/sfn/callback/stack_policy.rb:35:in …
```
> Fix save stack policy

- lib/sfn/config.rb
Hi,
I noticed that my comma delimited parameters where being incorrectly parsed when I was passing them in the CLI.
```
bundle exec sfn create --parameters CDLKey:Value1,Value2,Value3,AnotherKey2:AnotherValue1
```
In that example my `CDLKey` would only get assigned the value of `Value1` and not the full comma-delimited value of `Value1,Value2,Value3`.
With this proposed fix (using a positive lookahead) the values passed to `Smash` are correctly mapped and sent to the provider.
Thanks,
> Fix comma-delimited parameter type parsing coming from the CLI

- lib/sfn/command_module/stack.rb
- lib/sfn/command_module/template.rb
Before and after-
```
SparkleFormation.new(:test, :provider => :aws).load(:base).overrides do
parameters do
SshKey do
type 'String'
end
end
end
[Sfn]: Callback template stack_policy: starting
[Sfn]: Callback template stack_policy: complete
[Sfn]: SparkleFormation: create
[Sfn]:   -> Name: test
[Sfn]: Stack runtime parameters: - template: test
[ERROR]: Value cannot be blank
[ERROR]: Value cannot be blank
[ERROR]: Value cannot be blank
[ERROR]: Value cannot be blank
[ERROR]: Value cannot be blank
[ERROR]: Value cannot be blank
[FATAL]: Failed to receive allowed parameter!
[Sfn]: Callback template stack_policy: starting
[Sfn]: Callback template stack_policy: complete
[Sfn]: SparkleFormation: create
[Sfn]:   -> Name: test
[Sfn]: Stack runtime parameters: - template: test
[ERROR]: SshKey: …
```
> Remember to say which parameter failed validation

- .travis.yml
- lib/sfn.rb
- lib/sfn/command.rb
- lib/sfn/command/import.rb
- lib/sfn/command/plan.rb
- lib/sfn/command/realize.rb
- lib/sfn/command/update.rb
- lib/sfn/command_module/planning.rb
- lib/sfn/command_module/stack.rb
- lib/sfn/command_module/template.rb
- lib/sfn/config.rb
- lib/sfn/config/plan.rb
- lib/sfn/config/realize.rb
- lib/sfn/error.rb
Split the `plan` command into two separate commands: `plan` and `realize`. The `plan` command still supports realizing generated plan in one step.
> Split plan into two commands

- lib/sfn/planner/aws.rb
- test/specs/planner_spec.rb
The stack trace of the error:
```
NoMethodError: undefined method `last' for nil:NilClass
/home/dualbus/src/sparkleformation/sfn/lib/sfn/planner/aws.rb:518:in `block in diff_init'
/home/dualbus/src/sparkleformation/sfn/lib/sfn/planner/aws.rb:513:in `tap'
/home/dualbus/src/sparkleformation/sfn/lib/sfn/planner/aws.rb:513:in `diff_init'
/home/dualbus/src/sparkleformation/sfn/lib/sfn/planner/aws.rb:541:in `register_diff'
/home/dualbus/src/sparkleformation/sfn/lib/sfn/planner/aws.rb:447:in `block in run_stack_diff'
/home/dualbus/src/sparkleformation/sfn/lib/sfn/planner/aws.rb:446:in `each'
/home/dualbus/src/sparkleformation/sfn/lib/sfn/planner/aws.rb:446:in `run_stack_diff'
/home/dualbus/src/sparkleformation/sfn/lib/sfn/planner/aws.rb:374:in `plan_stack' …
```
> Add test case for `NoMethodError` crash in diff_init

- lib/sfn/command/validate.rb
- lib/sfn/config/validate.rb
I'm not sure if this method of collecting all the template names is too naive. It seems like it should work. 
closes #2
> Add --all flag to validate all templates

- lib/sfn/command/plan.rb
Description:
In my `.sfn.rb`, I have set an option capabilities 
```
Configuration.new do
options do
capabilities ['CAPABILITY_IAM']
end
end
```
When I executed `rake sfn:plan`, I get the following error message showing I'm missing the capabilities option even though I have it set in `.sfn.rb`
```
[ERROR]: Bad Request - InsufficientCapabilitiesException: Requires capabilities : [CAPABILITY_IAM]
```
This is because `plan.rb` did not capture any options set in `.sfn.rb` so that's why I get the bad request with missing capabilities error.
Fix is to capture options defined in `.sfn.rb` and `sfn:plan` works.
/cc @chrisroberts
> bug: plan did not capture options passed into .sfn.rb
